vim.keymap.set('n', '<leader>m', '<cmd> lua require("harpoon.mark").add_file()<CR>', {})
vim.keymap.set('n', '<leader>1', '<cmd> lua require("harpoon.ui").nav_file(1)<CR>', {})
vim.keymap.set('n', '<leader>2', '<cmd> lua require("harpoon.ui").nav_file(2)<CR>', {})
vim.keymap.set('n', '<leader>3', '<cmd> lua require("harpoon.ui").nav_file(3)<CR>', {})
vim.keymap.set('n', '<leader>4', '<cmd> lua require("harpoon.ui").nav_file(4)<CR>', {})
vim.keymap.set('n', 'M', '<cmd> lua require("harpoon.ui").toggle_quick_menu()<CR>', {})
